name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at midnight UTC every Monday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Fetch Upstream Remote
        run: |
          git remote add upstream https://github.com/gradle/actions.git
          git fetch upstream

      - name: Merge Upstream `main` 
        run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "GitHub Actions"
          
          git checkout main
          git merge upstream/main --no-commit
          git reset -- ./.github
          git commit -m "Merge in upstream/main"
          git push
